server:
  port: 8080

spring:
  application:
    name: payment-service-app

  datasource: # объединяет в себе параметры подключения к БД
    url: jdbc:postgresql://localhost:5433/payment-db # URL подключения к БД
    username: admin # Имя пользователя
    password: secret # Пароль
    driver-class-name: org.postgresql.Driver # класс jdbc драйвера

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/iprody-lms

logging:
  level:
    com.iprody.paymentserviceapp: DEBUG
    org.springframework.web: INFO
    org.springframework.data: INFO
    org.springframework.security: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
