version: '3.8'

services:
  payment-service-app:
    image: payment-service-app
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin         # имя пользователя
      POSTGRES_PASSWORD: secret    # пароль
      POSTGRES_DB: payment-db      # имя БД по умолчанию
    ports:
      - "5433:5432"                # проброс порта PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com    # учётка для входа
      PGADMIN_DEFAULT_PASSWORD: admin           # пароль для входа
    ports:
      - "8081:80"              # UI будет доступен по localhost:8081
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
