name: Build Project for PR

on:
  # Запуск при создании или обновлении PR в ветку main
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Шаг 3: Компиляция проекта (без тестов)
      - name: Compile with Maven
        working-directory: ./payment-service
        run: mvn -B clean compile

      # Шаг 4: Запуск тестов
      - name: Run tests
        working-directory: ./payment-service
        run: mvn -B test

      # Шаг 5: Запуск Checkstyle
      - name: Run Checkstyle for payment-service-app
        working-directory: ./payment-service/payment-service-app
        run: mvn -B checkstyle:check